server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.10.7:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.nxyf.springcloud.com.nxyf.springcloud.entities
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true  #单节点无所谓，集群必须配置未true才能配合ribbon进行负载均衡
  instance:
    instance-id: payment8001  #主机名
    prefer-ip-address: true #显示IP
    lease-renewal-interval-in-seconds: 1  #发送心跳间隔
    lease-expiration-duration-in-seconds: 2 #eureka服务端在收到最后一次心跳后，等待时间上限，超时将剔除