server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
#    alibaba:
#      #自定义事务组名称需要与seata-server中的对应
    nacos:
      discovery:
        server-addr: 192.168.101.108:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.101.108:3306/seata_order
    username: root
    password: root
seata:
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 192.168.101.108:8091
    enable-degrade: false
    disable-global-transaction: false
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.101.108:8848
      group: "SEATA_GROUP"
      namespace: "6de48216-f950-4983-8dec-ca053112b499"
      username: "nacos"
      password: "nacos"
  config:
    type: nacos
    nacos:
      server-addr: 192.168.101.108:8848
      group : "SEATA_GROUP"
      namespace: "6de48216-f950-4983-8dec-ca053112b499"
      username: "nacos"
      password: "nacos"
  enable-auto-data-source-proxy: false
  tx-service-group: my_test_tx_group
  enabled: true
  application-id: ${spring.application.name}
feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
